### PR TITLE
Add Type: Module to Package.Json

### PR DESCRIPTION
**Pull request by ingalls**
:wave: Hey @mapsam,

Thanks a ton for the TS migration, it's wonderful to replace my shims! The current version (2.0.0) is causing some issues with my deploy tooling as the TS package uses Module `exports` syntax without declaring itself a module.

I've added the `type: module` in the package.json required to allow use of `exports` instead of `module.exports`

### CODE REVIEW

**Comment by mapsam** [comment]
Woops thanks for the ping @ingalls, sorry about the error there! I'm no longer able to merge these PRs, but maybe @greenlaw or @AlexanderBelokon can take a look.

**Comment by ingalls** [comment]
I saw that after I cut this PR!! Congrats on the new gig!

**Comment by greenlaw** [comment]
@ingalls I think this will break CJS imports if merged, is that your understanding?

We just went through this on another repo and ended up using a dual-packaging approach.  Can you take a look here and see if the same approach would work for you here?  https://github.com/mapbox/sphericalmercator/pull/47

**Comment by ingalls** [comment]
@greenlaw Yes, you are correct, my head is 100% into ESM so I haven't dealt with compat with CJS in a bit but your approach in SM seems like the way to go to retain CJS support.

**Comment by greenlaw** [comment]
@ingalls  That would be great - thanks

**Comment by ingalls** [comment]
@greenlaw I've updated the PR with the same dual ESM/CJS approach you took in the SM library. Let me know if this looks good to you! Thanks all!

**Comment by greenlaw** [comment]
@ingalls Looks good, just two minor things:

- I think we can keep the `prepublishOnly` script
- Could you bump the version to `2.0.1` and `npm i` to update `package-lock.json` again?

Happy to approve/merge once that's done.

**Comment by ingalls** [comment]
@greenlaw done.

**Review by greenlaw — APPROVED** [review]
Thanks @ingalls !

**Comment by greenlaw** [comment]
v2.0.1 has been published 👍

**Pull request merged**
